Build kind image
Signed-off-by: Sameer <sameer.khan@broadcom.com>

diff --git a/.github/workflows/test-gh.yml b/.github/workflows/test-gh.yml
--- a/.github/workflows/test-gh.yml
+++ b/.github/workflows/test-gh.yml
@@ -29,6 +29,19 @@ jobs:
           echo "Resolved latest k8s version to: $k8s_version"
         fi
         echo "k8s_version=$k8s_version" >> $GITHUB_ENV
+    - name: Build and push kind image for latest Kubernetes
+      run: |
+        k8s_version=v1.35.0-beta.0
+        mkdir tmp && cd tmp
+        git clone https://github.com/kubernetes/kubernetes.git && cd kubernetes
+        git checkout v1.35.0-beta.0
+        git clone https://github.com/kubernetes-sigs/kind.git && cd kind
+        kind build node-image --type=source $(pwd)/.. --image kindest/node:v1.35.0-beta.0
+        docker tag kindest/node:v1.35.0-beta.0 \
+          ghcr.io/${{ github.repository_owner }}/kindest-node:v1.35.0-beta.0
+        docker push ghcr.io/${{ github.repository_owner }}/kindest-node:v1.35.0-beta.0
+        cd $(pwd)/../../../
+        rm -rf tmp && echo "Cleanup completed: Temporary directory 'tmp' has been removed." || echo "Cleanup failed: Could not remove 'tmp' directory."
     - name: Create Kind Cluster(k8s version ${{ env.k8s_version }})
       run: |
         k8s_version=${{ env.k8s_version }}
