Fix trivy github action failure (#370)
* Fix trivy github action failure

Fix trivy github action failure

* Update trivy-scan.yml

* Update trivy-scan.yml

diff --git a/.github/workflows/trivy-scan.yml b/.github/workflows/trivy-scan.yml
--- a/.github/workflows/trivy-scan.yml
+++ b/.github/workflows/trivy-scan.yml
@@ -23,50 +23,56 @@ jobs:
 
       - name: Build the kapp binary file
         run: |
+          # Build kapp Binary File
           ./hack/build.sh
 
-      - name: Run Trivy vulnerability scanner in repo mode
-        uses: aquasecurity/trivy-action@master
-        with:
-          scan-type: 'fs'
-          input: '.'
-          ignore-unfixed: true
-          format: 'template'
-          template: '@/contrib/sarif.tpl'
-          output: 'trivy-results.sarif'
-          severity: 'CRITICAL,HIGH,MEDIUM'
-          # Ignoring the go.sum file as it may contain the older dependencies entries which are not being used now.
-          skip-dirs: 'go.sum'
-
+      - name: Install trivy
+        run: |
+          # Download trivy binary.
+          brew install aquasecurity/trivy/trivy
+          
+          # Create trivy binary file
+          git clone --depth 1 https://github.com/aquasecurity/trivy
+        
+      - name: Run trivy to generate reports
+        run: |  
+          # Generate trivy report in sarif format
+          trivy rootfs --ignore-unfixed --format template --template  "@trivy/contrib/sarif.tpl" --output trivy-results.sarif kapp
+          
+          # Generate trivy report in json format
+          trivy rootfs --ignore-unfixed --format json --output results.json kapp
+      
       - name: Upload Trivy scan results to GitHub Security tab
         uses: github/codeql-action/upload-sarif@v1
         with:
           sarif_file: 'trivy-results.sarif'
 
-      - name: Run Trivy to generate report for slack Notification
-        uses: aquasecurity/trivy-action@master
-        with:
-          scan-type: 'fs'
-          input: '.'
-          ignore-unfixed: true
-          format: json
-          output: 'results.json'
-          # Ignoring the go.sum file as it may contain the older dependencies entries which are not being used now.
-          skip-dirs: 'go.sum'
-
       - name: Create Issues Summary
         run: |
-          summary=$(jq '.[] | select(.Vulnerabilities) | .Vulnerabilities | group_by(.Severity) | map({Severity: .[0].Severity, Count: length}) | tostring' results.json | tr -d \\)
+          # We should fail the github action even if there is an issue with `jq` parsing. Hence set -o pipefail
+          set -o pipefail
+          summary=$(jq '.Results[] | select(.Vulnerabilities) | .Vulnerabilities | group_by(.Severity) | map({Severity: .[0].Severity, Count: length}) | tostring' results.json | tr -d \\)
+          
           if [ -z $summary ]
           then
             summary="0 Issues"
           fi
           echo "SUMMARY=$summary" >> $GITHUB_ENV
-
-      - name: Send Slack Notification
+      
+      - name: Send Slack Notification if Scan Ran Successfully
+        if: success()
         uses: slackapi/slack-github-action@v1.15.0
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
         with:
           channel-id: C026Z8V6XPE
           slack-message: "Trivy Scan Summary is: ${{ env.SUMMARY }} "
+          
+      - name: Send Slack Notification if Scan Failed
+        if: failure()
+        uses: slackapi/slack-github-action@v1.15.0
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
+        with:
+          channel-id: C026Z8V6XPE
+          slack-message: "Trivy Scan Github Workflow is failing. Please look into it."
